version: '3'

services:
    frontend:
        container_name: vue_frontend
        build:
            context: .
            dockerfile: frontend.dockerfile
        ports:
            - "5000:5000"
        networks:
            - net

networks:
    net: